# Generated by Django 3.1.7 on 2021-03-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iccard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('id_card', models.CharField(max_length=45)),
                ('cardnum', models.CharField(max_length=45)),
                ('birthday', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('carddate', models.CharField(max_length=45)),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
                ('pressures', models.IntegerField(db_column='pressureS')),
                ('pressured', models.IntegerField(db_column='pressureD')),
                ('testdate', models.DateTimeField()),
                ('heartbeat', models.IntegerField()),
            ],
            options={
                'db_table': 'iccard',
                'managed': False,
            },
        ),
    ]
